### ISSUE TITLE
Ungodly loud

### ISSUE THREAD

**Issue by EllieShrug** [viliger2/RoR2_Catacombs#1]
the sound effects do not respect ror2's option menu. destroyed my ears.

**Comment by viliger2** [comment]
I've checked and both music and sound effects follow their respective sound settings in addition to following master volume. They are a bit loud in Wwise tho, I admit. I will lower their volume by 10 db in the next update.

**Comment by viliger2** [comment]
Lowered volume of all sounds with 1.0.1. Check if it still blows your ears off.

**Comment by Tishbyte** [comment]
Can confirm. Fire sounds are at max volume and don't change with in-game volume. I was playing with someone else (I was hosting) and they weren't affected.

**Comment by viliger2** [comment]
Oh, you mean torches. I completely forgot about them and forgot that they even make any sort of sound. Yes, those do not use Wwise, I'll fix it in the next update then, they will use Wwise and as result will follow sound effect volume setting.

**Comment by viliger2** [comment]
Should be fixed with 1.0.2.
